main:
  category_features:
    [
      "workclass",
      "education",
      "marital-status",
      "occupation",
      "relationship",
      "race",
      "sex",
      "native-country",
    ]
  label: "salary"
  model_path: "model/lr_model.pkl"
  slice_output_path: "slice_output.txt"
  data_path: "data/census_clean.csv"
  test_size: 0.2
